/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4;
import java.util.HashSet;

/**
 *
 * @author Keke
 */
public class DesktopPaneEscritorio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DesktopPaneEscritorio.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private static HashSet<Alumno> listaAlumnos;
    private static HashSet<Materia> listaMaterias;
    public DesktopPaneEscritorio() {
        initComponents();
        listaAlumnos = new HashSet<>();
        listaMaterias = new HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMenuAgrAlum = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMenuItemAgrMateria = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemInscripcion = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");

        jMenuAgrAlum.setText("Agregar Alumno");
        jMenuAgrAlum.addActionListener(this::jMenuAgrAlumActionPerformed);
        jMenuAlumno.add(jMenuAgrAlum);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materia");

        jMenuItemAgrMateria.setText("Agregar Materias");
        jMenuItemAgrMateria.addActionListener(this::jMenuItemAgrMateriaActionPerformed);
        jMenuMateria.add(jMenuItemAgrMateria);

        jMenuBar1.add(jMenuMateria);

        jMenuRegistro.setText("Registro");

        jMenuItemInscripcion.setText("Vista Inscripcion");
        jMenuItemInscripcion.addActionListener(this::jMenuItemInscripcionActionPerformed);
        jMenuRegistro.add(jMenuItemInscripcion);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAgrAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgrAlumActionPerformed
        InternalFrameMenuAlumno verAlumnos = new InternalFrameMenuAlumno(listaAlumnos);
        escritorio.add(verAlumnos);
        verAlumnos.setVisible(true);
    }//GEN-LAST:event_jMenuAgrAlumActionPerformed

    private void jMenuItemAgrMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgrMateriaActionPerformed
        // TODO add your handling code here:
        
        InternalFrameMenuMaterias verMaterias = new InternalFrameMenuMaterias(listaMaterias);
        escritorio.add(verMaterias);
        verMaterias.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgrMateriaActionPerformed

    private void jMenuItemInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscripcionActionPerformed
        // TODO add your handling code here:
        InternalFrameMenuInscripcion verInscripcion = new InternalFrameMenuInscripcion(listaAlumnos, listaMaterias);

        escritorio.add(verInscripcion);
        verInscripcion.setVisible(true);
    }//GEN-LAST:event_jMenuItemInscripcionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DesktopPaneEscritorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuAgrAlum;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgrMateria;
    private javax.swing.JMenuItem jMenuItemInscripcion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}

